### ISSUE TITLE
RHCOS 4.x ARM / ppc64le - Jenkins not ready after 5000 MILLISECONDS

### ISSUE THREAD

**Issue by mike-nguyen** [openshift/os#1029]
We are seeing this consistently now in our builds for ppc64le.

```
io.fabric8.kubernetes.client.KubernetesClientException: not ready after 5000 MILLISECONDS
	at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:176)
	at io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener.waitUntilReady(ExecWebSocketListener.java:158)
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:329)
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:84)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1.doLaunch(ContainerExecDecorator.java:421)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1.launch(ContainerExecDecorator.java:338)
```

**Comment by mike-nguyen** [comment]
Likely due to https://issues.jenkins.io/browse/JENKINS-67664 which is fixed in 3690.va_9ddf6635481.  We we cannot update to due to incompatibility issues between `openshift-sync`, `kubernetes` and `kubernetes-client-api`. The openshift-sync plugin which syncs the RHCOS buildconfigs into Jenkins jobs is only compatible with specific `kubernetes` and `kubernetes-client-api` plugin versions.

**Comment by mike-nguyen** [comment]
More details: https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/client-and-managed-masters/considerations-for-kubernetes-clients-connection-when-using-kubernetes-plugin

**Comment by mike-nguyen** [comment]
Possible workarounds to reduce the occurrence of the error:

**Comment by mike-nguyen** [comment]
Cluster issues were resolved.
