### ISSUE TITLE
Unable to use pivot or docker for rebasing into container content

### ISSUE THREAD

**Issue by peterbaouoft** [openshift/os#157]
Hi, 
As title suggests, I was unable to use pivot/(docker + rebase) locally. Below is the method I have tried. 
```
-------docker login is done earlier ------
[root@localhost ~]# ./pivot registry.svc.ci.openshift.org/rhcos/os:latest
pivot version 0.0.0 (56ac45679f34297b39fdc74b874900efa33eb8e5)
Running: skopeo inspect docker://registry.svc.ci.openshift.org/rhcos/os:latest
Trying to pull registry.svc.ci.openshift.org/rhcos/os:latest@sha256:05815042ae65eabac9c1406b7a8cc8fae45345407fe95cc939367f2d2a031ea2...Getting image source signatures
Copying blob sha256:9fd0835072117c2226c8ae1334aaf880e02edbba573329c3e3bcb7f6136a0dac
 71.23 MB / 71.23 MB [======================================================] 8s
Copying blob sha256:b3ccca4efa9f6752e8706e6de91a5db79717ce248517a4e9f374f06e7dca7097
 709.60 MB / 709.60 MB [=================================================] 1m27s
Copying config sha256:03b98184dc2939e423efefaa044d31ed06d717ee09351affab5b68ed0b7562c6
 2.21 KB / 2.21 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
03b98184dc2939e423efefaa044d31ed06d717ee09351affab5b68ed0b7562c6
Running: podman run -d --name ostree-container-pivot --entrypoint sleep registry.svc.ci.openshift.org/rhcos/os:latest@sha256:05815042ae65eabac9c1406b7a8cc8fae45345407fe95cc939367f2d2a031ea2 infinity
Running: podman mount 83ff4446d6fd4bec3d90f74c340b0e853d1a0a9546b76fcd22ff6bd662416152
Running: ostree --repo=srv/tree/repo refs
error: /var/lib/containers/storage/overlay/8ffccd95b35cabd32a7ff839004623a483a1b1d85b5bc5bc49cd651fb705d73b/merged/srv/tree/repo: opendir(/var/lib/containers/storage/overlay/8ffccd95b35cabd32a7ff839004623a483a1b1d85b5bc5bc49cd651fb705d73b/merged/srv/tree/repo): No such file or directory
F0706 14:33:40.715089    2900 run.go:34] ostree: exit status 1
goroutine 1 [running]:
github.com/ashcrow/pivot/vendor/github.com/golang/glog.stacks(0xc420016e00, 0xc420066a20, 0x3f, 0x10b)
	/home/steve/Tech/Envs/go/src/github.com/ashcrow/pivot/vendor/github.com/golang/glog/glog.go:769 +0xa7
github.com/ashcrow/pivot/vendor/github.com/golang/glog.(*loggingT).output(0x6e7d40, 0xc400000003, 0xc420094160, 0x6c99d8, 0x6, 0x22, 0x0)
	/home/steve/Tech/Envs/go/src/github.com/ashcrow/pivot/vendor/github.com/golang/glog/glog.go:720 +0x36b
github.com/ashcrow/pivot/vendor/github.com/golang/glog.(*loggingT).printf(0x6e7d40, 0xc400000003, 0x5ee520, 0x6, 0xc4200cb7e8, 0x2, 0x2)
	/home/steve/Tech/Envs/go/src/github.com/ashcrow/pivot/vendor/github.com/golang/glog/glog.go:655 +0x14f
github.com/ashcrow/pivot/vendor/github.com/golang/glog.Fatalf(0x5ee520, 0x6, 0xc4200cb7e8, 0x2, 0x2)
	/home/steve/Tech/Envs/go/src/github.com/ashcrow/pivot/vendor/github.com/golang/glog/glog.go:1148 +0x67
github.com/ashcrow/pivot/utils.RunGetOut(0x5ee742, 0x6, 0xc4200cbab0, 0x2, 0x2, 0xc4200438f0, 0x6b)
	/home/steve/Tech/Envs/go/src/github.com/ashcrow/pivot/utils/run.go:34 +0x310
github.com/ashcrow/pivot/cmd.Execute(0x6e58c0, 0xc420083a70, 0x1, 0x1)
	/home/steve/Tech/Envs/go/src/github.com/ashcrow/pivot/cmd/root.go:89 +0x5e2
github.com/ashcrow/pivot/vendor/github.com/spf13/cobra.(*Command).execute(0x6e58c0, 0xc42000a1d0, 0x1, 0x1, 0x6e58c0, 0xc42000a1d0)
	/home/steve/Tech/Envs/go/src/github.com/ashcrow/pivot/vendor/github.com/spf13/cobra/command.go:766 +0x2b9
github.com/ashcrow/pivot/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x6e58c0, 0x4, 0x6ce500, 0xc420083a20)
	/home/steve/Tech/Envs/go/src/github.com/ashcrow/pivot/vendor/github.com/spf13/cobra/command.go:852 +0x37e
github.com/ashcrow/pivot/vendor/github.com/spf13/cobra.(*Command).Execute(0x6e58c0, 0xb, 0x5ee21a)
	/home/steve/Tech/Envs/go/src/github.com/ashcrow/pivot/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/steve/Tech/Envs/go/src/github.com/ashcrow/pivot/main.go:25 +0x154
[root@localhost ~]# rpm-ostree status
State: idle; auto updates disabled
Deployments:
* ostree://fedora-atomic:fedora/28/x86_64/atomic-host
                   Version: 28.20180527.0 (2018-05-27 19:05:29)
                    Commit: 291ea90da29bc5abe757b5a50813b3de1396b08412939a89b3b671aba9856093
              GPGSignature: Valid signature by 128CF232A9371991C8A65695E08E7E629DB62FB1
```

As above suggests, the image seems to be pulling down correctly, but neither `pivot or docker way` are able to rebase/use the `/repo` content from the container. I have seen this behaviour for two hosts.. Am I missing something? Thanks :).

**Comment by jlebon** [comment]
Ahh, I think this is a regression from #153. The repo is now at `/srv/repo`, but `pivot` is looking in `/srv/tree/repo`: https://github.com/ashcrow/pivot/blob/master/cmd/root.go#L88.

Feel like opening a patch there to fix it up? :)

**Comment by peterbaouoft** [comment]
> Feel like opening a patch there to fix it up? :) 

Sure, lemme try it :)

**Comment by peterbaouoft** [comment]
Close because of https://github.com/ashcrow/pivot/pull/8. Will reopen if regression is needed =).
