### ISSUE TITLE
RHCOS 4.11 + kata-containers dependency failure

### ISSUE THREAD

**Issue by miabbott** [openshift/os#750]
Just hit a failure on the RHCOS 4.11 build pipeline when trying to build the extensions:

<details>

```
+ cosa buildextend-extensions
Running: rpm-ostree compose extensions --repo=/home/jenkins/agent/workspace/rhcos-art/rhcos-art-rhcos-4.11/tmp/repo --touch-if-changed tmp/extensions/changed --cachedir=/home/jenkins/agent/workspace/rhcos-art/rhcos-art-rhcos-4.11/cache src/config/manifest.yaml src/config/extensions.yaml --base-rev 6d8459c483fa0c6e0b19f1ce0da155a693f77c26e3372b290b4e5e972c9e5dd6 --output-dir tmp/extensions/output
Checking out 6d8459c... done!
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
Enabled rpm-md repositories: rhel-8-server-ose rhel-8-advanced-virt rhel-8-fast-datapath rhel-8-baseos rhel-8-appstream rhel-8-nfv
Updating metadata for 'rhel-8-server-ose'...done
Updating metadata for 'rhel-8-advanced-virt'...done
Updating metadata for 'rhel-8-fast-datapath'...done
Updating metadata for 'rhel-8-baseos'...done
Updating metadata for 'rhel-8-appstream'...done
Updating metadata for 'rhel-8-nfv'...done
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
Importing rpm-md...done
rpm-md repo 'rhel-8-server-ose'; generated: 2022-03-17T17:49:53Z solvables: 399
rpm-md repo 'rhel-8-advanced-virt'; generated: 2022-03-16T14:01:10Z solvables: 2188
rpm-md repo 'rhel-8-fast-datapath'; generated: 2022-02-24T17:43:03Z solvables: 655
rpm-md repo 'rhel-8-baseos'; generated: 2022-03-16T15:34:25Z solvables: 11069
rpm-md repo 'rhel-8-appstream'; generated: 2022-03-17T17:26:10Z solvables: 24397
rpm-md repo 'rhel-8-nfv'; generated: 2022-03-10T14:49:24Z solvables: 597
Resolving dependencies...done
[0m[31merror: [0mCould not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides qemu-kvm-core >= 15:6.2.0 needed by kata-containers-2.3.3-2.el8.x86_64
Traceback (most recent call last):
  File "/usr/lib/coreos-assembler/cmd-buildextend-extensions", line 124, in <module>
    sys.exit(main())
  File "/usr/lib/coreos-assembler/cmd-buildextend-extensions", line 40, in main
    changed = run_rpmostree(tmpworkdir, commit, treefile_src, extensions_src)
  File "/usr/lib/coreos-assembler/cmd-buildextend-extensions", line 83, in run_rpmostree
    cmdlib.cmdlib_sh(f'''
  File "/usr/lib/coreos-assembler/cosalib/cmdlib.py", line 350, in cmdlib_sh
    subprocess.check_call(['bash', '-c', f'''
  File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', '-c', '\n        set -euo pipefail\n        source /usr/lib/coreos-assembler/cosalib/../cmdlib.sh\n        \n        changed_stamp=tmp/extensions/changed\n        runcompose_extensions tmp/extensions/output src/config/manifest.yaml src/config/extensions.yaml             --base-rev 6d8459c483fa0c6e0b19f1ce0da155a693f77c26e3372b290b4e5e972c9e5dd6\n    ']' returned non-zero exit status 1.
[Pipeline] }
```

</details>

It appears the `kata-containers` RPM was updated to require `qemu-kvm-core-6.2`, but the repos we are using don't have that version available.  (Remember we are currently using RHEL 8.5 content while we wait for RHEL 8.6 to be made available.)

@etrunko is there a recommended solution for this while we are still using RHEL 8.5?  Perhaps we just pin to an older version of `kata-containers` until we can switch to RHEL 8.6?

**Comment by etrunko** [comment]
I pushed a change to the package, specifying the epoch of qemu-kvm-core version, which caused this problem. I will revert it for now and it should be okay until we are not able to switch to RHEL 8.6.

**Comment by etrunko** [comment]
kata-containers-2.3.3-3 should fix this problem.

**Comment by miabbott** [comment]
We're getting successful builds in CI and in the downstream pipeline now that the new `kata-containers` package has been built.
