### ISSUE TITLE
RHCOS 4.11 x86_64: pushing oscontainer started failing

### ISSUE THREAD

**Issue by miabbott** [openshift/os#847]
Seeing the following:

```
[Pipeline] sh
+ cosa push-container --format v2s2 --base-image quay.io/openshift-release-dev/ocp-v4.0-art-dev
skopeo copy --authfile /srv/.reg/..2022_06_14_10_18_47.895472488/docker.json --format v2s2 --digestfile=/home/jenkins/agent/workspace/rhcos-art/rhcos-art-rhcos-4.11/tmp/push-container-digestfileff8e6izc oci-archive:builds/411.86.202206141020-0/x86_64/rhcos-411.86.202206141020-0-ostree.x86_64.ociarchive docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev-base-image
Getting image source signatures
time="2022-06-14T11:26:09Z" level=fatal msg="trying to reuse blob sha256:b624eae845d9d661e55983e728dcd8fa3da8f57d88b26106af68a84947b8ec75 at destination: checking whether a blob sha256:b624eae845d9d661e55983e728dcd8fa3da8f57d88b26106af68a84947b8ec75 exists in quay.io/openshift-release-dev/ocp-v4.0-art-dev-base-image: unauthorized: authentication required"
Traceback (most recent call last):
  File "/usr/lib/coreos-assembler/cmd-push-container", line 60, in <module>
    subprocess.check_call(skopeoargs)
  File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['skopeo', 'copy', '--authfile', '/srv/.reg/..2022_06_14_10_18_47.895472488/docker.json', '--format', 'v2s2', '--digestfile=/home/jenkins/agent/workspace/rhcos-art/rhcos-art-rhcos-4.11/tmp/push-container-digestfileff8e6izc', 'oci-archive:builds/411.86.202206141020-0/x86_64/rhcos-411.86.202206141020-0-ostree.x86_64.ociarchive', 'docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev-base-image']' returned non-zero exit status 1.
```

Looking at the last successful oscontainer push, it was using https://github.com/coreos/coreos-assembler/commit/22a85ec7bd4109428b64fc9cdb6f08b9be2136b5.

Started to fail with https://github.com/coreos/coreos-assembler/commit/4a6477ea6087015a376d433ae64300d50c47f9dc

Looks like fallout from coreos/coreos-assembler#2907

cc: @cgwalters

**Comment by ravanelli** [comment]
The image is missing the RHCOS version. It is trying to push to `quay.io/openshift-release-dev/ocp-v4.0-art-dev-base-image` instead of `quay.io/openshift-release-dev/ocp-v4.0-art-dev-411.86.202206141020-0-x86_64-base-image`

Seems some issue when we try to create the tag using `tag = ":${build[0]}-baseimage` in the internal gitlab repo (upshift/osbuild.groovy#L456). The build[0] looks to be empty

**Comment by cgwalters** [comment]
PR in https://github.com/coreos/coreos-assembler/pull/2917

**Comment by miabbott** [comment]
Looks like the new `--name-suffix` behavior from coreos/coreos-assembler#2923 is not the same as the `--base-image` behavior as before.

The `--base-image` behavior was adding the extra string to the tag:

```
+ cosa push-container --format v2s2 --base-image quay.io/openshift-release-dev/ocp-v4.0-art-dev
skopeo copy --authfile /srv/.reg/..2022_06_13_14_31_37.581779626/docker.json --format v2s2 oci-archive:builds/411.86.202206131434-0/x86_64/rhcos-411.86.202206131434-0-ostree.x86_64.ociarchive docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev:411.86.202206131434-0-x86_64-base-image
```

The `--name-suffix` behavior is appending the string to the image name:

```
+ cosa push-container --format=v2s2 --name-suffix=base-image quay.io/openshift-release-dev/ocp-v4.0-art-dev
skopeo copy --authfile /srv/.reg/..2022_06_15_07_58_57.057068507/docker.json --format v2s2 --digestfile=/home/jenkins/agent/workspace/rhcos-art/rhcos-art-rhcos-4.11/tmp/push-container-digestfile_nhyy4f0 oci-archive:builds/411.86.202206150800-0/x86_64/rhcos-411.86.202206150800-0-ostree.x86_64.ociarchive docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev-base-image:411.86.202206150800-0-x86_64
```

This is causing the downstream RHCOS pipeline to fail.

cc: @jlebon

**Comment by jlebon** [comment]
https://github.com/coreos/coreos-assembler/pull/2925
