### ISSUE TITLE
RHCOS 4.10 - kola test `rhcos.upgrade.from-ocp-rhcos` failing

### ISSUE THREAD

**Issue by mike-nguyen** [openshift/os#857]
```
--- FAIL: rhcos.upgrade.from-ocp-rhcos (3.59s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x1a13670]

goroutine 237 [running]:
github.com/coreos/mantle/harness.tRunner.func1(0xc000747b80)
	/root/containerbuild/mantle/harness/harness.go:470 +0x2fe
panic(0x1e15d80, 0x347a140)
	/usr/lib/golang/src/runtime/panic.go:965 +0x1b9
github.com/coreos/mantle/kola/tests/rhcos.downloadLatestReleasedRHCOS(0xc000050057, 0x49, 0x0, 0x0, 0x0, 0x0)
	/root/containerbuild/mantle/kola/tests/rhcos/upgrade.go:376 +0x850
github.com/coreos/mantle/kola/tests/rhcos.rhcosUpgradeFromOcpRhcos(0xc000747b80, 0x26489a8, 0xc000e00300, 0x0, 0x0, 0x0, 0x1)
	/root/containerbuild/mantle/kola/tests/rhcos/upgrade.go:212 +0x1ab
github.com/coreos/mantle/kola.runTest(0xc000747b80, 0xc0005ccb60, 0x7fffc585cac7, 0xb, 0x263d418, 0xc0007b4850)
	/root/containerbuild/mantle/kola/harness.go:1333 +0xb51
github.com/coreos/mantle/kola.runProvidedTests.func1(0xc000747b80)
	/root/containerbuild/mantle/kola/harness.go:632 +0x7f
github.com/coreos/mantle/harness.tRunner(0xc000747b80, 0xc00055ec90)
	/root/containerbuild/mantle/harness/harness.go:512 +0x104
created by github.com/coreos/mantle/harness.(*H).RunTimeout
	/root/containerbuild/mantle/harness/harness.go:557 +0x38e
qemu-system-x86_64: terminating on signal 15 from pid 21544 ()
qemu-system-x86_64: terminating on signal 15 from pid 21544 ()
qemu-system-x86_64: tpm-emulator: Could not cleanly shutdown the TPM: Input/output error
qemu-system-x86_64: tpm-emulator: Could not cleanly shutdown the TPM: Invalid argument
```

This test looks at the upgrade graph and determines the latest Y stream released version. My investigation shows that the test is correctly getting the latest version, [4.10.18](https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.10.18), which shows to be running RHCOS 410.84.202206080346-0 , however this version actually does not exist in the release browser.
```
Components
- Kubernetes 1.23.5
- Red Hat Enterprise Linux CoreOS upgraded from 410.84.202206010432-0 to 410.84.202206080346-0 (diff)
```
Jenkins doesn't go back far enough but it seems like the build should not have been promoted into a nightly build.

From @miabbott:
> This sounds like a case of the oscontainer being built and pushed, but the whole of the pipeline failing so that builds.json + meta.json was never pushed

**Comment by cgwalters** [comment]
4.10 build is green, I assume we're good here
