### ISSUE TITLE
RHCOS 9.0: Boot fails on `error: Found argument '--rereadpt' which wasn't expected, or isn't valid in this context`

### ISSUE THREAD

**Issue by travier** [openshift/os#979]
This is a "pure" RHEL 9.0 CoreOS for 4.12 build (only with skopeo on top).

```
         Starting Ignition (disks)...
[    4.289263] ignition[919]: Ignition 2.13.0
[    4.290324] ignition[919]: Stage: disks
[    4.291160] ignition[919]: reading system config file "/usr/lib/ignition/base.d/00-core.ign"
[    4.292947] ignition[919]: no config dir at "/usr/lib/ignition/base.platform.d/qemu"
[  OK      4.294539] ignition[919]: disks: disks passed
0m] Finished Ignition (disks).
[    4.295924] systemd[1]: Finished Ignition (disks).
[    4.296922] ignition[919]: Ignition finished successfully
[  OK      4.298096] systemd[1]: Reached target Initrd Root Device.
0m] Reached target Initrd Root Device.
[    4.301518] systemd[1]: Starting CoreOS Ensure Unique Boot Filesystem...
         Starting CoreOS Ensure Unique Boot Filesystem...
[    4.304906] rdcore[925]: error: Found argument '--rereadpt' which wasn't expected, or isn't valid in this context
[    4.306396] rdcore[925]: USAGE:
[FAILED] Failed to [    4.307102] rdcore[925]:     rdcore verify-unique-fs-label <LABEL>
start C[    4.308360] rdcore[925]: For more information try --help
oreOS Ensure Uni[    4.309396] systemd[1]: coreos-ignition-unique-boot.service: Main process exited, code=exited, status=1/FAILURE
que Boot Filesys[    4.311062] systemd[1]: coreos-ignition-unique-boot.service: Failed with result 'exit-code'.
tem.[    4.312547] systemd[1]: Failed to start CoreOS Ensure Unique Boot Filesystem.

See 'systemctl status coreos-ignition-unique-boot.service' for details.
[    4.314398] systemd[1]: Dependency failed for Ignition Boot Disk Setup.
[DEPEND] Dependency failed for Ignition Boot Disk Setup.
[    4.316189] systemd[1]: Dependency failed for Ignition Complete.
[DEPEND] Dependency failed for Ignition Complete.
[[    4.317853] systemd[1]: Dependency failed for Initrd Default Target.
```

**Comment by travier** [comment]
We're likely missing some RHEL 9 backports for coreos-installer & Ignition.

**Comment by travier** [comment]
Potential culprits (packages with a higher version in the rhaos repo than in RHEL) in this list:
```
  afterburn-5.3.0-1.rhaos4.12.el8.x86_64 (rhel-8-server-ose)
  afterburn-dracut-5.3.0-1.rhaos4.12.el8.x86_64 (rhel-8-server-ose)
  conmon-2:2.1.2-2.rhaos4.11.el8.x86_64 (rhel-8-server-ose)
  containernetworking-plugins-1.0.1-5.rhaos4.11.el8.x86_64 (rhel-8-server-ose)
  coreos-installer-0.15.0-2.rhaos4.12.el8.x86_64 (rhel-8-server-ose)
  coreos-installer-bootinfra-0.15.0-2.rhaos4.12.el8.x86_64 (rhel-8-server-ose)
  fuse-overlayfs-1.9-1.rhaos4.11.el8.x86_64 (rhel-8-server-ose)
  ignition-2.14.0-4.rhaos4.12.el8.x86_64 (rhel-8-server-ose)
  ostree-2022.2-5.el8.x86_64 (rhel-8-server-ose)
  ostree-grub2-2022.2-5.el8.x86_64 (rhel-8-server-ose)
  ostree-libs-2022.2-5.el8.x86_64 (rhel-8-server-ose)
  podman-2:4.2.0-1.rhaos4.12.el8.x86_64 (rhel-8-server-ose)
  podman-catatonit-2:4.2.0-1.rhaos4.12.el8.x86_64 (rhel-8-server-ose)
  skopeo-2:1.8.0-1.rhaos4.12.el8.x86_64 (rhel-8-server-ose)
```

**Comment by bgilbert** [comment]
`--rereadpt` was added in coreos-installer 0.13.0, which was released in February.  Looks like you also have a stale Ignition; 2.14.0 was released in May.

**Comment by cgwalters** [comment]
This is RHEL 9.0 right?  Released in May but frozen a while before that, so that seems expected. 

We have new enough things in C9S and queued for 9.1 I'd assume.

I think we need to tag the required things from 9.1 into `rhaos-4.12-rhel-9`.

**Comment by travier** [comment]
Maybe we can backport what we need into 9.0? Otherwise we'll have to do that again for 4.13

**Comment by travier** [comment]
Triggered the backport process for:
- https://bugzilla.redhat.com/show_bug.cgi?id=2101940
- https://bugzilla.redhat.com/show_bug.cgi?id=2081063
- https://bugzilla.redhat.com/show_bug.cgi?id=2090647
- https://bugzilla.redhat.com/show_bug.cgi?id=2070964

**Comment by cgwalters** [comment]
Wait but why can't we just ship what we want from 9.1 earlier?

**Comment by cgwalters** [comment]
I had this issue in mind when I did https://github.com/openshift/os/pull/985 too - basically we add a `rhel-9` entry there too...

**Comment by travier** [comment]
Well, 9.1 is not released yet.

**Comment by cgwalters** [comment]
But we can ship things built for 9.1 early if we have approval from the owner of the package/code.

**Comment by HuijingHei** [comment]
Just add comment for `cosa buildextend-live` failed on RHCOS9, as stale `coreos-installer-0.11.0-4.el9.x86_64.rpm` in RHEL9.0
```
chroot /sysroot/ostree/deploy/rhcos/deploy/2d8755ce5c5284b7642883683b8814f5910b8dd0fb7714886f17bea9ea98d4ed.0 coreos-installer pack osmet /dev/disk/by-id/virtio-osmet --description 'Red Hat Enterprise Linux CoreOS 412.90.202209090155-0 (Plow)' --checksum c9e587fc4d7c8b3c6ac0a9a5a0fe0722f32247b878b58b10c37576ac7035e776 --output /tmp/osmet.bin
error: Found argument 'pack' which wasn't expected, or isn't valid in this context
USAGE:
    coreos-installer
    coreos-installer <SUBCOMMAND>
For more information try --help
2022-09-09 02:23:06,176 ERROR - Command returned bad exitcode
2022-09-09 02:23:06,176 ERROR - COMMAND: ['/usr/lib/coreos-assembler/osmet-pack', 'builds/412.90.202209090155-0/x86_64/rhcos-412.90.202209090155-0-metal.x86_64.raw', '512', '/tmp/cosa/tmp/buildpost-live/initrd-rootfs/rhcos-412.90.202209090155-0-metal.x86_64.raw.osmet', 'c9e587fc4d7c8b3c6ac0a9a5a0fe0722f32247b878b58b10c37576ac7035e776', 'normal']
Traceback (most recent call last):
  File "/usr/lib/coreos-assembler/cmd-buildextend-live", line 712, in <module>
    generate_iso()
  File "/usr/lib/coreos-assembler/cmd-buildextend-live", line 300, in generate_iso
    runcmd(['/usr/lib/coreos-assembler/osmet-pack',
  File "/usr/lib/coreos-assembler/cosalib/cmdlib.py", line 78, in runcmd
    raise e
  File "/usr/lib/coreos-assembler/cosalib/cmdlib.py", line 70, in runcmd
    cp = subprocess.run(cmd, **pargs)
  File "/usr/lib64/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/lib/coreos-assembler/osmet-pack', 'builds/412.90.202209090155-0/x86_64/rhcos-412.90.202209090155-0-metal.x86_64.raw', '512', '/tmp/cosa/tmp/buildpost-live/initrd-rootfs/rhcos-412.90.202209090155-0-metal.x86_64.raw.osmet', 'c9e587fc4d7c8b3c6ac0a9a5a0fe0722f32247b878b58b10c37576ac7035e776', 'normal']' returned non-zero exit status 1.
error: failed to execute cmd-buildextend-live: exit status 1
```

**Comment by travier** [comment]
We now have a too old version of rpm-ostree in RHEL 9

**Comment by travier** [comment]
```
podman build --file extensions/Dockerfile --from "registry.ci.openshift.org/rhcos-devel/rhel-coreos-9-oci:${TAG}" .
WARN[0000] missing "COSA" build argument. Try adding "--build-arg COSA=<VALUE>" to the command line 
[1/3] STEP 1/7: FROM registry.ci.openshift.org/rhcos-devel/rhel-coreos-9-oci:412.90.202210190758-0 AS os
[1/3] STEP 2/7: RUN mkdir /os
--> Using cache 39694d6b0652eed7d268005433be237dbaf39240cc3a9ce3587dedc069d9ad75
--> 39694d6b065
[1/3] STEP 3/7: WORKDIR /os
--> Using cache e636f7a1f2761269bbb1cdf4860170e7b1653cfd8aab558b86e4b4d5bf71494e
--> e636f7a1f27
[1/3] STEP 4/7: ADD . .
--> 2a0456c6b64
[1/3] STEP 5/7: ARG COSA
--> 358f30f3215
[1/3] STEP 6/7: RUN if [[ -z "$COSA" ]] && [[ ! -f "ocp.repo" ]]; then ci/get-ocp-repo.sh ; fi
--> defb9799619
[1/3] STEP 7/7: RUN rpm-ostree compose extensions --rootfs=/ --output-dir=/usr/share/rpm-ostree/extensions/ {manifest,extensions}.yaml
error: Unknown option --rootfs=/
Error: error building at STEP "RUN rpm-ostree compose extensions --rootfs=/ --output-dir=/usr/share/rpm-ostree/extensions/ {manifest,extensions}.yaml": error while running runtime: exit status 1
```

**Comment by cgwalters** [comment]
FWIW I have edited every single comment in this issue to clarify that we're talking about *9.0* with a zero.
